### ISSUE TITLE
Fix NPE issue on BeerOrderLine when placing order

### ISSUE THREAD

**Issue by Griesba** [Griesba/griesba-beer-order-service#1]
java.lang.NullPointerException: null
	at com.griesba.brewery.beer.order.service.services.BeerOrderServiceImpl.placeOrder(BeerOrderServiceImpl.java:62) ~[classes/:na]
	at com.griesba.brewery.beer.order.service.services.TastingRoomService.placeOrder(TastingRoomService.java:68) ~[classes/:na]
	at com.griesba.brewery.beer.order.service.services.TastingRoomService.placeTastingRoomOrder(TastingRoomService.java:45) ~[classes/:na]
	at com.griesba.brewery.beer.order.service.services.TastingRoomService$$FastClassBySpringCGLIB$$83ee793.invoke(<generated>) ~[classes/:na]
	at org.springframework.cglib.proxy.MethodProxy.invoke(MethodProxy.java:218) ~[spring-core-5.2.10.RELEASE.jar:5.2.10.RELEASE]

**Comment by Griesba** [comment]
Issue related to mapstruct not mapping lombock @Builder annotation
